- name: Create Production Server
  hosts: 178.128.39.186
  roles:
    - { name: repos }
    - { name: git }
    - { name: node }
    - { name: php, install_xdebug: no, prov_env: production }
    - { name: users, prov_env: production}
    - { name: server_folder_structure, prov_env: production }
    - { name: nginx }
    - { name: code_deploy_keys }
    - { name: code_deploy, prov_env: production }
    - { name: selinux }
  vars_prompt:
    - name: "site_url"
      prompt: "What is the site url?"
      private: false
