---
- hosts: php
  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - nginx
      - php5-cli
      - php5-fpm

  - name: install node
    shell: wget -qO- https://deb.nodesource.com/setup_7.x | sudo bash - && apt-get install -y nodejs
    sudo: yes
    sudo_user: root

  - group:
      name: personal-site-app
      state: present

  - name: creating personal-site-app user
    user:
      name: personal-site-app
      shell: /bin/bash
      group: personal-site-app

  - group:
      name: nginx
      state: present

  - name: creating nginx user
    user:
      name: nginx
      shell: /bin/bash
      group: nginx

  - group:
      name: personal-site-app-fpm
      state: present

  - name: creating personal-site-app-fpm user
    user:
      name: personal-site-app-fpm
      shell: /bin/bash
      group: personal-site-app-fpm

  #may no longer be required
  - name: add fpm user to group
    user:
      name: personal-site-app-fpm
      group: personal-site-app
      append: yes

  - name: create /opt/sites directory
    file: dest=/opt/sites/ state=directory owner=personal-site-app group=personal-site-app
    sudo: yes
    sudo_user: root

  - name: create ssh
    file: dest=~/.ssh state=directory owner=personal-site-app group=personal-site-app mode=0700
    sudo: yes
    sudo_user: personal-site-app

  - name: put deployment key onto server 2
    copy: src=/Users/andrewtaylor/.ssh/codeymccodeface dest=~/.ssh/codeymccodeface owner=personal-site-app mode=0600
    sudo: yes
    sudo_user: personal-site-app

  - name: create known hosts
    file: dest=~/.ssh/known_hosts state=touch owner=personal-site-app group=personal-site-app mode=0600
    sudo: yes
    sudo_user: personal-site-app

  - name: ssh-keyscan the git server #https://github.com/ansible/ansible/issues/7474
    shell: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
    sudo: yes
    sudo_user: personal-site-app

  - name: Clone git repository
    git: >
      dest=/opt/sites/personal-website
      repo=git@bitbucket.org:andrewjt71/personal-website.git
      update=no
      key_file=~/.ssh/codeymccodeface
    sudo: yes
    sudo_user: personal-site-app
    register: cloned

  - name: Deploy app
    shell: cd /opt/sites/personal-website && ./bin/deploy
    sudo: yes
    sudo_user: personal-site-app

  - name: update php-fpm user 1
    lineinfile:
      path: /etc/php5/fpm/pool.d/www.conf
      regexp: '^user ='
      line: 'user = personal-site-app-fpm'

  #had to set group to shared group for logs
  - name: update php-fpm group 1
    lineinfile:
      path: /etc/php5/fpm/pool.d/www.conf
      regexp: '^group ='
      line: 'group = personal-site-app'

  - name: update php-fpm user 2
    lineinfile:
      path: /etc/php5/fpm/pool.d/www.conf
      regexp: '^listen.owner ='
      line: 'listen.owner = nginx'

  - name: update php-fpm group 2
    lineinfile:
      path: /etc/php5/fpm/pool.d/www.conf
      regexp: '^listen.group ='
      line: 'listen.group = nginx'

  - name: listen mode
    lineinfile:
      path: /etc/php5/fpm/pool.d/www.conf
      regexp: '^listen.mode ='
      line: 'listen.mode = 0660'

  - name: update nginx user
    lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^user'
      line: 'user nginx;'
  
  - name: Configure nginx
    template: src=nginx.conf dest=/etc/nginx/sites-available/default
    notify:
      - restart php5-fpm
      - restart nginx

  handlers:
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
