- name: Create VM
  hosts: 192.168.33.99
  roles:
    - { name: repos }
    - { name: git }
    - { name: node }
    - { name: php, install_xdebug: no, prov_env: production }
    - { name: users, prov_env: vm }
    - { name: server_folder_structure }
    - { name: nginx }
    - { name: selinux }
    - { name: code_deploy, prov_env: vm }

  vars_prompt:
    - name: "site_url"
      prompt: "What is the site url?"
      private: false
