- name: Create Production Server
  hosts: codeymccodeface.co.uk
  roles:
    - { name: repos }
    - { name: git }
    - { name: node }
    - { name: php, install_xdebug: no, prov_env: production }
    - { name: users, prov_env: production}
    - { name: server_folder_structure, prov_env: production }
    - { name: nginx }
    - { name: ssh_access }
    - { name: selinux }
  vars_prompt:
    - name: "site_url"
      prompt: "What is the site url?"
      private: false
