install_php_fpm: no
install_xdebug: no

php_packages:
  - php72u-cli
  - php72u-pdo
  - php72u-xml
  - php72u-json
#  - php72u-xmlrpc
#  - php72u-common
#  - php72u-gd
#  - php72u-mbstring
#  - php72u-mcrypt
#  - php72u-mysqlnd
#  - php72u-opcache
#  - php72u-pear
#  - php72u-process
#  - php72u-soap
#  - php72u-bcmath

xdebug_package: php72u-xdebug
php_fpm_package: php72u-fpm

prop_env: vm
