- include_vars: vars/production.yml
  when: prov_env == 'production'

- include_vars: vars/vm.yml
  when: prov_env == 'vm'

- name: creating deploy group
  group:
    name: deploy
    state: present

- name: creating deploy user
  user:
    name: deploy
    shell: /bin/bash
    groups: '{{ user_groups_for_deploy }}'
